PW_KEYS = {
    "CONTROL": [
        "calculation",
        "title",
        "verbosity",
        "restart_mode",
        "wf_collect",
        "nstep",
        "iprint",
        "tstress",
        "tprnfor",
        "dt",
        "outdir",
        "wfcdir",
        "prefix",
        "lkpoint_dir",
        "max_seconds",
        "etot_conv_thr",
        "forc_conv_thr",
        "disk_io",
        "pseudo_dir",
        "tefield",
        "dipfield",
        "lelfield",
        "nberrycyc",
        "lorbm",
        "lberry",
        "gdir",
        "nppstr",
        "lfcpopt",
        "monopole",
    ],
    "SYSTEM": [
        "ibrav",
        "nat",
        "ntyp",
        "nbnd",
        "tot_charge",
        "tot_magnetization",
        "starting_magnetization",
        "ecutwfc",
        "ecutrho",
        "ecutfock",
        "nr1",
        "nr2",
        "nr3",
        "nr1s",
        "nr2s",
        "nr3s",
        "nosym",
        "nosym_evc",
        "noinv",
        "no_t_rev",
        "force_symmorphic",
        "use_all_frac",
        "occupations",
        "one_atom_occupations",
        "starting_spin_angle",
        "degauss",
        "smearing",
        "nspin",
        "noncolin",
        "ecfixed",
        "qcutz",
        "q2sigma",
        "input_dft",
        "exx_fraction",
        "screening_parameter",
        "exxdiv_treatment",
        "x_gamma_extrapolation",
        "ecutvcut",
        "nqx1",
        "nqx2",
        "nqx3",
        "lda_plus_u",
        "lda_plus_u_kind",
        "Hubbard_U",
        "Hubbard_J0",
        "Hubbard_alpha",
        "Hubbard_beta",
        "Hubbard_J",
        "starting_ns_eigenvalue",
        "U_projection_type",
        "edir",
        "emaxpos",
        "eopreg",
        "eamp",
        "angle1",
        "angle2",
        "constrained_magnetization",
        "fixed_magnetization",
        "lambda",
        "report",
        "lspinorb",
        "assume_isolated",
        "esm_bc",
        "esm_w",
        "esm_efield",
        "esm_nfit",
        "fcp_mu",
        "vdw_corr",
        "london",
        "london_s6",
        "london_c6",
        "london_rvdw",
        "london_rcut",
        "ts_vdw_econv_thr",
        "ts_vdw_isolated",
        "xdm",
        "xdm_a1",
        "xdm_a2",
        "space_group",
        "uniqueb",
        "origin_choice",
        "rhombohedral",
        "zmon",
        "realxz",
        "block",
        "block_1",
        "block_2",
        "block_height",
    ],
    "ELECTRONS": [
        "electron_maxstep",
        "scf_must_converge",
        "conv_thr",
        "adaptive_thr",
        "conv_thr_init",
        "conv_thr_multi",
        "mixing_mode",
        "mixing_beta",
        "mixing_ndim",
        "mixing_fixed_ns",
        "diagonalization",
        "ortho_para",
        "diago_thr_init",
        "diago_cg_maxiter",
        "diago_david_ndim",
        "diago_full_acc",
        "efield",
        "efield_cart",
        "efield_phase",
        "startingpot",
        "startingwfc",
        "tqr",
    ],
    "IONS": [
        "ion_dynamics",
        "ion_positions",
        "pot_extrapolation",
        "wfc_extrapolation",
        "remove_rigid_rot",
        "ion_temperature",
        "tempw",
        "tolp",
        "delta_t",
        "nraise",
        "refold_pos",
        "upscale",
        "bfgs_ndim",
        "trust_radius_max",
        "trust_radius_min",
        "trust_radius_ini",
        "w_1",
        "w_2",
    ],
    "CELL": [
        "cell_dynamics",
        "press",
        "wmass",
        "cell_factor",
        "press_conv_thr",
        "cell_dofree",
    ],
}


PH_KEYS = {
    "INPUTPH": [
        "amass",
        "outdir",
        "prefix",
        "niter_ph",
        "tr2_ph",
        "alpha_mix",
        "nmix_ph",
        "verbosity",
        "reduce_io",
        "max_seconds",
        "dftd3_hess",
        "fildyn",
        "fildrho",
        "fildvscf",
        "epsil",
        "lrpa",
        "lnoloc",
        "trans",
        "lraman",
        "eth_rps",
        "eth_ns",
        "dek",
        "recover",
        "low_directory_check",
        "only_init",
        "qplot",
        "q2d",
        "q_in_band_form",
        "electron_phonon",
        "el_ph_nsigma",
        "el_ph_sigma",
        "ahc_dir",
        "ahc_nbnd",
        "ahc_nbndskip",
        "skip_upperfan",
        "lshift_q",
        "zeu",
        "zue",
        "elop",
        "fpol",
        "ldisp",
        "nogg",
        "asr",
        "ldiag",
        "lqdir",
        "search_sym",
        "nq1",
        "nq2",
        "nq3",
        "nk1",
        "nk2",
        "nk3",
        "k1",
        "k2",
        "k3",
        "diagonalization",
        "read_dns_bare",
        "ldvscf_interpolate",
        "wpot_dir",
        "do_long_range",
        "do_charge_neutral",
        "start_irr",
        "last_irr",
        "nat_todo",
        "modenum",
        "start_q",
        "last_q",
        "dvscf_star",
        "drho_star",
    ]
}

PP_KEYS = {
    "INPUTPP": [
        "prefix",
        "outdir",
        "filplot",
        "plot_num",
        "spin_component",
        "spin_component",
        "emin",
        "emax",
        "delta_e",
        "degauss_ldos",
        "use_gauss_ldos",
        "sample_bias",
        "kpoint",
        "kband",
        "lsign",
        "spin_component",
        "emin",
        "emax",
        "spin_component",
        "spin_component",
        "spin_component",
        "spin_component",
    ],
    "PLOT": [
        "nfile",
        "filepp",
        "weight",
        "iflag",
        "output_format",
        "fileout",
        "interpolation",
        "e1",
        "x0",
        "nx",
        "e1",
        "e2",
        "x0",
        "nx",
        "ny",
        "e1",
        "e2",
        "e3",
        "x0",
        "nx",
        "ny",
        "nz",
        "radius",
        "nx",
        "ny",
    ],
}

MATDYN_KEYS = {
    "INPUT": [
        "flfrc",
        "asr",
        "huang",
        "dos",
        "nk1",
        "nk2",
        "nk3",
        "deltae",
        "ndos",
        "degauss",
        "fldos",
        "flfrq",
        "flvec",
        "fleig",
        "fldyn",
        "at",
        "l1",
        "l2",
        "l3",
        "ntyp",
        "amass",
        "readtau",
        "fltau",
        "la2f",
        "q_in_band_form",
        "q_in_cryst_coord",
        "eigen_similarity",
        "fd",
        "na_ifc",
        "nosym",
        "loto_2d",
        "loto_disable",
        "read_lr",
        "write_frc",
    ]
}


DYNMAT_KEYS = {
    "INPUT": [
        "fildyn",
        "q",
        "amass",
        "asr",
        "remove_interaction_blocks",
        "axis",
        "lperm",
        "lplasma",
        "filout",
        "fileig",
        "filmol",
        "filxsf",
        "loto_2d",
        "el_ph_nsig",
        "el_ph_sigma",
    ]
}


Q2R_KEYS = {"INPUT": ["fildyn", "flfrc", "zasr", "loto_2d", "write_lr"]}

DOS_KEYS = {
    "&DOS": [
        "prefix",
        "outdir",
        "bz_sum",
        "ngauss",
        "degauss",
        "emin",
        "emax",
        "deltae",
        "fildos",
    ]
}


BANDS_KEYS = {
    "&BANDS": [
        "prefix",
        "outdir",
        "filband",
        "spin_component",
        "lsigma",
        "lp",
        "filp",
        "lsym",
        "no_overlap",
        "plot_2d",
        "firstk",
        "lastk",
    ]
}


BAND_INTERPOLATION_KEYS = {
    "INTERPOLATION": [
        "method",
        "miller_max",
        "check_periodicity",
        "p_metric",
        "scale_sphere",
    ]
}


PROJWFC_KEYS = {
    "PROJWFC": [
        "prefix",
        "outdir",
        "ngauss",
        "degauss",
        "emin",
        "emax",
        "deltae",
        "lsym",
        "diag_basis",
        "pawproj",
        "filpdos",
        "filproj",
        "lwrite_overlaps",
        "lbinary_data",
        "kresolveddos",
        "tdosinboxes",
        "n_proj_boxes",
        "irmin",
        "irmax",
        "plotboxes",
    ]
}


MOLECULARPDOS_KEYS = {
    "INPUTMOPDOS": [
        "xmlfile_full",
        "xmlfile_part",
        "i_atmwfc_beg_full",
        "i_atmwfc_end_full",
        "i_atmwfc_beg_part",
        "i_atmwfc_end_part",
        "i_bnd_beg_full",
        "i_bnd_end_full",
        "i_bnd_beg_part",
        "i_bnd_end_part",
        "fileout",
        "ngauss",
        "degauss",
        "emin",
        "emax",
        "deltae",
        "kresolveddos",
    ]
}


IMPORTEXPORT_BINARY_KEYS = {"INPUTPP": ["prefix", "outdir", "direction", "newoutdir"]}


OSCDFT_PP_KEYS = {"OSCDFT_PP_NAMELIST": ["prefix", "outdir"]}

KCW_KEYS = {
    "CONTROL": [
        "prefix",
        "outdir",
        "calculation",
        "kcw_iverbosity",
        "kcw_at_ks",
        "read_unitary_matrix",
        "spread_thr",
        "homo_only",
        "l_vcut",
        "assume_isolated",
        "spin_component",
        "mp1",
        "mp2",
        "mp3",
        "lrpa",
    ],
    "WANNIER": [
        "seedname",
        "num_wann_occ",
        "num_wann_emp",
        "have_empty",
        "has_disentangle",
        "check_ks",
    ],
    "SCREEN": ["niter", "nmix", "tr2", "i_orb", "eps_inf", "check_spread"],
    "HAM": ["do_bands", "use_ws_distance", "write_hr", "on_site_only"],
}


CPPP_KEYS = {
    "INPUTPP": [
        "prefix",
        "fileout",
        "output",
        "outdir",
        "lcharge",
        "lforces",
        "ldynamics",
        "lpdb",
        "lrotation",
        "np1",
        "np2",
        "np3",
        "nframes",
        "ndr",
        "atomic_number",
    ]
}


PPACF_KEYS = {
    "PPACF": [
        "prefix",
        "outdir",
        "n_lambda",
        "lplot",
        "ltks",
        "lfock",
        "use_ace",
        "code_num",
        "vdw_analysis",
    ]
}


ALL_CURRENTS_KEYS = {
    "ENERGY_CURRENT": [
        "delta_t",
        "file_output",
        "trajdir",
        "vel_input_units",
        "eta",
        "n_max",
        "first_step",
        "last_step",
        "step_mul",
        "step_rem",
        "ethr_small_step",
        "ethr_big_step",
        "restart",
        "subtract_cm_vel",
        "add_i_current_b",
        "save_dvpsi",
        "re_init_wfc_1",
        "re_init_wfc_2",
        "re_init_wfc_3",
        "three_point_derivative",
        "n_repeat_every_step",
        "n_workers",
        "worker_id",
        "continue_not_converged",
    ]
}


TURBO_LANCZOS_KEYS = {
    "LR_INPUT": [
        "prefix",
        "outdir",
        "wfcdir",
        "restart",
        "restart_step",
        "lr_verbosity",
        "disk_io",
    ],
    "LR_CONTROL": [
        "itermax",
        "ipol",
        "n_ipol",
        "ltammd",
        "no_hxc",
        "lrpa",
        "scissor",
        "charge_response",
        "pseudo_hermitian",
        "d0psi_rs",
        "lshift_d0psi",
    ],
    "LR_POST": ["omeg", "epsil", "beta_gamma_z_prefix", "w_t_npol", "plot_type"],
}


TURBO_SPECTRUM_KEYS = {
    "LR_INPUT": [
        "prefix",
        "outdir",
        "verbosity",
        "itermax0",
        "itermax",
        "extrapolation",
        "epsil",
        "units",
        "start",
        "end",
        "increment",
        "ipol",
        "eels",
        "magnons",
        "td",
        "eign_file",
    ]
}


TURBO_DAVIDSON_KEYS = {
    "LR_INPUT": [
        "prefix",
        "outdir",
        "wfcdir",
        "max_seconds",
        "restart",
        "lr_verbosity",
        "disk_io",
    ],
    "LR_DAV": [
        "num_eign",
        "num_init",
        "if_random_init",
        "num_basis_max",
        "residue_conv_thr",
        "precondition",
        "single_pole",
        "if_dft_spectrum",
        "reference",
        "broadening",
        "start",
        "finish",
        "step",
        "p_nbnd_occ",
        "p_nbnd_virt",
        "poor_of_ram",
        "poor_of_ram2",
        "max_iter",
        "no_hxc",
        "pseudo_hermitian",
        "ltammd",
        "lplot_drho",
        "d0psi_rs",
        "lshift_d0psi",
    ],
}


TURBO_MAGNON_KEYS = {
    "LR_INPUT": [
        "prefix",
        "outdir",
        "restart",
        "restart_step",
        "lr_verbosity",
        "disk_io",
    ],
    "LR_CONTROL": [
        "itermax",
        "pseudo_hermitian",
        "approximation",
        "ipol",
        "q1",
        "q2",
        "q3",
    ],
}


TURBO_EELS_KEYS = {
    "LR_INPUT": [
        "prefix",
        "outdir",
        "restart",
        "restart_step",
        "lr_verbosity",
        "disk_io",
    ],
    "LR_CONTROL": [
        "approximation",
        "q1",
        "q2",
        "q3",
        "calculator",
        "itermax",
        "pseudo_hermitian",
        "alpha_mix(i",
        "epsil",
        "units",
        "start",
        "end",
        "increment",
        "ethr_nscf",
    ],
}


OSCDFT_ET_KEYS = {
    "OSCDFT_ET_NAMELIST": [
        "initial_prefix",
        "final_prefix",
        "initial_dir",
        "final_dir",
        "print_matrix",
        "print_eigvect",
        "print_debug",
    ]
}


PPRISM_KEYS = {
    "INPUTPP": ["prefix", "outdir", "filplot", "lpunch"],
    "PLOT": [
        "iflag",
        "output_format",
        "fileout",
        "interpolation",
        "x0",
        "nx",
        "lebedev",
        "e1",
        "x0",
        "nx",
        "e1",
        "e2",
        "x0",
        "nx",
        "ny",
        "e1",
        "e2",
        "e3",
        "x0",
        "nx",
        "ny",
        "nz",
        "radius",
        "nx",
        "ny",
    ],
}


PWCOND_KEYS = {
    "INPUTCOND": [
        "outdir",
        "prefixt",
        "prefixl",
        "prefixs",
        "prefixr",
        "tran_prefix",
        "max_seconds",
        "recover",
        "band_file",
        "tran_file",
        "save_file",
        "fil_loc",
        "lwrite_cond",
        "loop_ek",
        "lread_cond",
        "lwrite_loc",
        "lread_loc",
        "ikind",
        "iofspin",
        "tk_plot",
        "llocal",
        "bdl",
        "bds",
        "bdr",
        "nz1",
        "energy0",
        "denergy",
        "nenergy",
        "start_e",
        "last_e",
        "start_k",
        "last_k",
        "ecut2d",
        "ewind",
        "epsproj",
        "orbj_in",
        "orbj_fin",
    ]
}


PW2BGW_KEYS = {
    "INPUT_PW2BGW": [
        "prefix",
        "outdir",
        "real_or_complex",
        "symm_type",
        "wfng_flag",
        "wfng_file",
        "wfng_kgrid",
        "wfng_nk1",
        "wfng_nk2",
        "wfng_nk3",
        "wfng_dk1",
        "wfng_dk2",
        "wfng_dk3",
        "wfng_occupation",
        "wfng_nvmin",
        "wfng_nvmax",
        "rhog_flag",
        "rhog_file",
        "rhog_nvmin",
        "rhog_nvmax",
        "vxcg_flag",
        "vxcg_file",
        "vxc0_flag",
        "vxc0_file",
        "vxc_flag",
        "vxc_file",
        "vxc_integral",
        "vxc_diag_nmin",
        "vxc_diag_nmax",
        "vxc_offdiag_nmin",
        "vxc_offdiag_nmax",
        "vxc_zero_rho_core",
        "vscg_flag",
        "vscg_file",
        "vkbg_flag",
        "vkbg_file",
    ]
}


BGW2PW_KEYS = {
    "INPUT_BGW2PW": [
        "prefix",
        "outdir",
        "real_or_complex",
        "wfng_flag",
        "wfng_file",
        "wfng_nband",
        "rhog_flag",
        "rhog_file",
    ]
}


HP_KEYS = {
    "INPUTHP": [
        "prefix",
        "outdir",
        "iverbosity",
        "max_seconds",
        "nq1",
        "nq2",
        "nq3",
        "skip_equivalence_q",
        "determine_num_pert_only",
        "determine_q_mesh_only",
        "find_atpert",
        "docc_thr",
        "skip_type",
        "equiv_type",
        "perturb_only_atom",
        "start_q",
        "last_q",
        "sum_pertq",
        "compute_hp",
        "conv_thr_chi",
        "thresh_init",
        "ethr_nscf",
        "niter_max",
        "alpha_mix(i",
        "nmix",
        "num_neigh",
        "lmin",
        "rmax",
        "dist_thr",
    ]
}


CP_KEYS = {
    "CONTROL": [
        "calculation",
        "title",
        "verbosity",
        "isave",
        "restart_mode",
        "nstep",
        "iprint",
        "tstress",
        "tprnfor",
        "dt",
        "outdir",
        "saverho",
        "prefix",
        "ndr",
        "ndw",
        "tabps",
        "max_seconds",
        "etot_conv_thr",
        "forc_conv_thr",
        "ekin_conv_thr",
        "disk_io",
        "memory",
        "pseudo_dir",
        "tefield",
    ],
    "SYSTEM": [
        "ibrav",
        "celldm",
        "a",
        "b",
        "c",
        "cosab",
        "cosac",
        "cosbc",
        "nat",
        "ntyp",
        "nbnd",
        "tot_charge",
        "tot_magnetization",
        "ecutwfc",
        "ecutrho",
        "nr1",
        "nr2",
        "nr3",
        "nr1s",
        "nr2s",
        "nr3s",
        "nr1b",
        "nr2b",
        "nr3b",
        "occupations",
        "degauss",
        "smearing",
        "nspin",
        "ecfixed",
        "qcutz",
        "q2sigma",
        "input_dft",
        "exx_fraction",
        "lda_plus_u",
        "hubbard_u",
        "vdw_corr",
        "london_s6",
        "london_rcut",
        "ts_vdw",
        "ts_vdw_econv_thr",
        "ts_vdw_isolated",
        "assume_isolated",
    ],
    "ELECTRONS": [
        "electron_maxstep",
        "electron_dynamics",
        "conv_thr",
        "niter_cg_restart",
        "efield",
        "epol",
        "emass",
        "emass_cutoff",
        "orthogonalization",
        "ortho_eps",
        "ortho_max",
        "ortho_para",
        "electron_damping",
        "electron_velocities",
        "electron_temperature",
        "ekincw",
        "fnosee",
        "startingwfc",
        "tcg",
        "maxiter",
        "passop",
        "pre_state",
        "n_inner",
        "niter_cold_restart",
        "lambda_cold",
        "grease",
        "ampre",
    ],
    "IONS": [
        "ion_dynamics",
        "ion_positions",
        "ion_velocities",
        "ion_damping",
        "ion_radius",
        "iesr",
        "ion_nstepe",
        "remove_rigid_rot",
        "ion_temperature",
        "tempw",
        "fnosep",
        "tolp",
        "nhpcl",
        "nhptyp",
        "nhgrp",
        "fnhscl",
        "ndega",
        "tranp",
        "amprp",
        "greasp",
    ],
    "CELL": [
        "cell_parameters",
        "cell_dynamics",
        "cell_velocities",
        "cell_damping",
        "press",
        "wmass",
        "cell_factor",
        "cell_temperature",
        "temph",
        "fnoseh",
        "greash",
        "cell_dofree",
    ],
    "PRESS_AI": [
        "abivol",
        "abisur",
        "p_ext",
        "pvar",
        "p_in",
        "p_fin",
        "surf_t",
        "rho_thr",
        "dthr",
    ],
    "WANNIER": [
        "wf_efield",
        "wf_switch",
        "sw_len",
        "efx0",
        "efy0",
        "efz0",
        "efx1",
        "efy1",
        "efz1",
        "wfsd",
        "wfdt",
        "maxwfdt",
        "nit",
        "nsd",
        "wf_q",
        "wf_friction",
        "nsteps",
        "tolw",
        "adapt",
        "calwf",
        "nwf",
        "wffort",
        "writev",
        "exx_neigh",
        "exx_dis_cutoff",
        "exx_poisson_eps",
        "exx_use_cube_domain",
        "exx_ps_rcut_self",
        "exx_ps_rcut_pair",
        "exx_me_rcut_self",
        "exx_me_rcut_pair",
    ],
}


LD1_KEYS = {
    "INPUT": [
        "title",
        "zed",
        "atom",
        "xmin",
        "dx",
        "rmax",
        "beta",
        "tr2",
        "iswitch",
        "nld",
        "rlderiv",
        "eminld",
        "emaxld",
        "deld",
        "rpwe",
        "rel",
        "lsmall",
        "max_out_wfc",
        "noscf",
        "lsd",
        "dft",
        "latt",
        "isic",
        "rytoev_fact",
        "cau_fact",
        "vdw",
        "prefix",
        "verbosity",
        "file_charge",
        "config",
        "relpert",
        "rel_dist",
        "write_coulomb",
    ],
    "INPUTP": [
        "zval",
        "pseudotype",
        "file_pseudopw",
        "file_recon",
        "lloc",
        "rcloc",
        "nlcc",
        "new_core_ps",
        "rcore",
        "tm",
        "rho0",
        "lpaw",
        "which_augfun",
        "rmatch_augfun",
        "rmatch_augfun_nc",
        "lsave_wfc",
        "lgipaw_reconstruction",
        "use_paw_as_gipaw",
        "author",
        "file_chi",
        "file_beta",
        "file_qvan",
        "file_screen",
        "file_core",
        "file_wfcaegen",
        "file_wfcncgen",
        "file_wfcusgen",
    ],
    "TEST": [
        "nconf",
        "file_pseudo",
        "ecutmin",
        "ecutmax",
        "decut",
        "rm",
        "configts",
        "lsdts",
        "frozen_core",
        "rcutv",
    ],
}


D3HESS_KEYS = {"INPUT": ["prefix", "outdir", "filhess", "step"]}

NEB_KEYS = {
    "PATH": [
        "string_method",
        "restart_mode",
        "nstep_path",
        "num_of_images",
        "opt_scheme",
        "ci_scheme",
        "first_last_opt",
        "minimum_image",
        "temp_req",
        "ds",
        "k_max",
        "k_min",
        "path_thr",
        "use_masses",
        "use_freezing",
        "lfcp",
        "fcp_mu",
        "fcp_thr",
        "fcp_scheme",
    ]
}


ALL_KEYS = {
    "pw": PW_KEYS,
    "ph": PH_KEYS,
    "pp": PP_KEYS,
    "matdyn": MATDYN_KEYS,
    "dynmat": DYNMAT_KEYS,
    "q2r": Q2R_KEYS,
    "dos": DOS_KEYS,
    "bands": BANDS_KEYS,
    "bands_interpolation": BAND_INTERPOLATION_KEYS,
    "projwfc": PROJWFC_KEYS,
    "molecularpdos": MOLECULARPDOS_KEYS,
    "importexport_binary": IMPORTEXPORT_BINARY_KEYS,
    "oscdft_pp": OSCDFT_PP_KEYS,
    "kcw": KCW_KEYS,
    "cppp": CPPP_KEYS,
    "ppacf": PPACF_KEYS,
    "all_currents": ALL_CURRENTS_KEYS,
    "turbo_lanczos": TURBO_LANCZOS_KEYS,
    "turbo_spectrum": TURBO_SPECTRUM_KEYS,
    "turbo_davidson": TURBO_DAVIDSON_KEYS,
    "turbo_magnon": TURBO_MAGNON_KEYS,
    "turbo_eels": TURBO_EELS_KEYS,
    "oscdft_et": OSCDFT_ET_KEYS,
    "pprism": PPRISM_KEYS,
    "pwcond": PWCOND_KEYS,
    "pw2bgw": PW2BGW_KEYS,
    "bgw2pw": BGW2PW_KEYS,
    "hp": HP_KEYS,
    "cp": CP_KEYS,
    "ld1": LD1_KEYS,
    "d3hess": D3HESS_KEYS,
    "neb": NEB_KEYS,
}
