#!/usr/bin/env python
"""
@author yingchun zhang
@e-mail yczhang@smail.nju.edu.cn
@org Nanjing University

"""
from ase import io
import numpy as np
from ase.calculators.singlepoint import SinglePointCalculator as spc

def get_energy(fileName):
    """
    open a .ener file generated by CP2K, and read into a list.
    
    """
    enerList = []
    file = open(fileName, 'r')
    for line in file:
        if line[0] != '#':
            enerList.append(float(line.split()[4]))

    file.close()
    return np.array(enerList)


def convert_to_traj(xyzfile, enerfile, trajfile, cell = [[10, 0, 0], [0, 10, 0], [0, 0, 10]], pbc = (1, 1, 1)):
    """
    read XYZ file generated by CP2K, and add energy of each configuration, then convert XYZ to traj file.

    """
    traj = io.Trajectory(trajfile, 'w')
    enerlist = get_energy(enerfile)
    for i in range(len(enerlist)):
        if i % 10 == 0:
            print 'process frame : %d' % i
        atoms = io.read(xyzfile, i)
        atoms.set_pbc(pbc)
        atoms.set_cell(cell)
        traj.write(atoms, energy = enerlist[i])
